version: "3.9"
services:
  mysql:
    image: mysql:latest
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lab1
      - MYSQL_TCP_PORT=3310
    ports:
      - "3310:3310"

  application:
    image: baliharko/bank:1.0.1
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_ROOT:PASSWORD=password
    ports:
      - "8080:8080"
    links:
      - mysql

  risk:
    image: daneidmark/risk:0.0.1
    ports:
      - "8082:8080"

