version: "3.9"
services:
  mysql:
    image: mysql
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lab1
      - MYSQL_TCP_PORT=3310
    ports:
      - "3310:3310"

  application:
    image: bank_app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_ROOT:PASSWORD=password
    ports:
      - "8080:8080"
    links:
      - mysql
