version: "3.9"
services:
  mysql:
    container_name: backend2_lab
#    image: mysql:8.0.26
    image: mysql:latest
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lab1
    ports:
      - "3308:3306"

  application:
    image: bank_app:latest
    environment:
       MYSQL_HOST: mysql
       MYSQL_ROOT:PASSWORD: password
    ports:
    - "8080:8080"
    depends_on:
    - mysql

#
#App
#  application:
#    container_name: bank_appd
#    image:
#    ports:
#    environment:
#
##Gui
#  frontend:
#    container_name:
#    image:
#
#
#
#

#    MYSQL_HOST: mysql
#        MYSQL_DATABASE: 'lab1_db'
#    # So you don't have to use root, but you can if you like
#    MYSQL_USER: 'root'
#    # You can use whatever password you like
#    MYSQL_PASSWORD: 'password'
#    # Password for root access
#    MYSQL_ROOT_PASSWORD: 'password'

#    test:
#      build: .
#      volumes:
#        environment:
#          depends_on: